/*
 * Pre-generates a pronunciation clip for every letter and word using a
 * free, keyless text-to-speech endpoint, and writes a manifest the site
 * loads. Doing this once at build time means the running site plays local
 * files and never depends on the endpoint being reachable from a browser.
 *
 * Run from the repo root:  node tools/generate-audio.mjs
 *
 * Language voices: Telugu (te) and Punjabi (pa) read their own script.
 * Odia has no free voice, so it is transliterated to the aligned
 * Devanagari and read with Hindi (hi), which lands on the same sounds.
 */
import { execFileSync } from 'node:child_process';
import { readFileSync, writeFileSync, mkdirSync, statSync } from 'node:fs';

// Load the character data by evaluating data.js against a window stub.
const win = {};
const dataSrc = readFileSync('scripts/data.js', 'utf8');
new Function('window', dataSrc)(win);
const DATA = win.BOLI_DATA;

function toDevanagari(s) {
  s = s.replace(/ଋ/g, 'रु').replace(/ୃ/g, '्रु');
  return s.replace(/[଀-୿]/g, (ch) => String.fromCharCode(ch.charCodeAt(0) - 0x200));
}
function voiceFor(langId, text) {
  if (langId === 'telugu') return { tl: 'te', say: text };
  if (langId === 'punjabi') return { tl: 'pa', say: text };
  return { tl: 'hi', say: toDevanagari(text) };   // odia
}
function ttsUrl(text, tl) {
  return 'https://translate.googleapis.com/translate_tts?ie=UTF-8&client=gtx&tl=' +
    tl + '&q=' + encodeURIComponent(text);
}

function fetchClip(url, outfile) {
  for (let attempt = 0; attempt < 3; attempt++) {
    try {
      execFileSync('curl', ['-s', '-A', 'Mozilla/5.0', '-o', outfile, url], { stdio: 'ignore' });
      if (statSync(outfile).size > 800) return true;   // real mp3, not an error page
    } catch (e) { /* retry */ }
    sleepMs(600);
  }
  return false;
}
function sleepMs(ms) { Atomics.wait(new Int32Array(new SharedArrayBuffer(4)), 0, 0, ms); }

// Build the full list of things to speak: every letter and every word.
const jobs = [];
DATA.languages.forEach((lang) => {
  DATA.groups.forEach((g) => {
    (DATA.chars[lang.id][g.key] || []).forEach((c) => {
      jobs.push({ lang: lang.id, glyph: c.glyph, id: c.id });
    });
  });
  (DATA.words[lang.id] || []).forEach((w, i) => {
    jobs.push({ lang: lang.id, glyph: w.w, id: lang.id + '.word.' + i });
  });
});

mkdirSync('audio', { recursive: true });
const manifest = {};
let ok = 0, fail = 0;
jobs.forEach((job, i) => {
  const outfile = 'audio/' + job.id + '.mp3';
  const { tl, say } = voiceFor(job.lang, job.glyph);
  if (fetchClip(ttsUrl(say, tl), outfile)) {
    manifest[job.lang + '|' + job.glyph] = outfile;
    ok++;
  } else {
    fail++;
    console.error('FAILED', job.id, job.glyph);
  }
  if (i % 20 === 0) console.log((i + 1) + '/' + jobs.length + ' ...');
  sleepMs(250);
});

const out = '/* Generated by tools/generate-audio.mjs. Maps "<lang>|<glyph>"\n' +
  ' * to a local clip so pronunciation never depends on a live service. */\n' +
  'window.BOLI_AUDIO = ' + JSON.stringify(manifest, null, 0) + ';\n';
writeFileSync('scripts/audio-manifest.js', out);
console.log('done. ok=' + ok + ' fail=' + fail + ' clips, manifest written.');
